version: '2'
services:
  grpcServerFullSpec:
    build: ../ContainerGrpcServerFullSpec/
    image: teamsaltstack:grpcServerFullSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_PORT=50001
    volumes:
      - ../ContainerGrpcServerFullSpec/volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcServer.js"
  grpcClientFullSpec:
    build: ../ContainerGrpcClientFullSpec/
    image: teamsaltstack:grpcClientFullSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - grpcServerFullSpec:grpcServer
    depends_on:
      -  grpcServerFullSpec
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_HOST=grpcServer
      - GRPC_SERVER_PORT=50001
    volumes:
      - ../ContainerGrpcClientFullSpec/volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcClient.js"


