version: '2'
services:
  grpcServerSupportedSpec:
    build: .
    image: teamsaltstack:grpcServerSupportedSpec
    ports:
      - "50001:50001"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_PORT=50001
    volumes:
      - ./volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcServer.js"

