version: '2'
services:
  grpcClientFullSpec:
    build: .
    image: teamsaltstack:grpcClientFullSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_HOST=192.169.10.21
      - GRPC_SERVER_PORT=50001
    volumes:
      - ./volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcClient.js"

