version: '2'
services:
  adapterGrpcServerFullSpec:
    build: ../ContainerGrpcServerSupportedSpec/
    image: teamsaltstack:adapterGrpcServerSupportedSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_PORT=50001
    volumes:
      - ../ContainerGrpcServerSupportedSpec/volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcServer.js"
  adapterGraphQlServer:
    build: ../ContainerGraphQlServer
    image: teamsaltstack:adapterGraphQlServer
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - adapterGrpcServerFullSpec:grpcServer
    depends_on:
      - adapterGrpcServerFullSpec
    environment:
      - API_HOST=grpcServer
      - API_PORT=50001
      - API_PROTO_PATH=/api/main.proto
    volumes:
      - ../ContainerGraphQlServer/volume:/api
    entrypoint:
      - "node"
      - "/fapra/graphQlServer.js"
      - "50002"
  adapterGraphQlClient:
    build: ../ContainerGraphQlClient
    image: teamsaltstack:adapterGraphQlClient
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - adapterGraphQlServer:graphQlServer
    depends_on:
      - adapterGrpcServerFullSpec
      - adapterGraphQlServer
    entrypoint:
      - "/fapra/callMethods.sh"
      - "graphQlServer"



