version: '2'
services:
  grpcServerFullSpec:
    build: .
    image: teamsaltstack:grpcServerFullSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "50001:50001"
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_PORT=50001
    volumes:
      - ./volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcServer.js"

