version: '2'
services:
  graphQlClient:
    build: .
    image: teamsaltstack:graphQlClient
    dns:
      - 8.8.8.8
      - 8.8.4.4
    entrypoint:
      - "/fapra/callMethods.sh"
      - "192.168.10.21"
