version: '2'
services:
  grpcServerSupportedSpec:
    build: ../ContainerGrpcServerSupportedSpec/
    image: teamsaltstack:grpcServerSupportedSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_PORT=50001
    volumes:
      - ../ContainerGrpcServerSupportedSpec/volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcServer.js"
  grpcClientSupportedSpec:
    build: ../ContainerGrpcClientSupportedSpec/
    image: teamsaltstack:grpcClientSupportedSpec
    dns:
      - 8.8.8.8
      - 8.8.4.4
    links:
      - grpcServerSupportedSpec:grpcServer
    depends_on:
      - grpcServerSupportedSpec
    environment:
      - API_PROTO_PATH=/api/main.proto
      - GRPC_SERVER_HOST=grpcServer
      - GRPC_SERVER_PORT=50001
    volumes:
      - ../ContainerGrpcClientSupportedSpec/volume:/api
    entrypoint:
      - "node"
      - "/fapra/grpcClient.js"


